### ISSUE TITLE
change/ choose piped instance

### ISSUE THREAD

**Issue by failafail8** [ts213/youtube-piped-redirect#1]
hey, i'd like to choose an other piped instance.
i use your extension from librewolf ( flatpak) and i didnt manage to find where is the file localy to change that line  
 return { redirectUrl: 'https://piped.video' + pathname + searchStr }
with the instance i want.
i tried to install addon from file, but i coulnt manage to do it aswell.
so i wonder if you can put an option to select the instance we want as done here : https://github.com/metiis/invidious-redirect
or if you may give me some tips on how to install your addon from file

sry for the newbie language and thanks for you addon.

**Comment by tsvtt** [comment]
Hi
You're on Linux? Try that path:
~/.var/app/io.gitlab.librewolf-community/.librewolf/<YOUR_PROFILE_ID>/extensions
Then find the addon and simply edit source code.

**Comment by tsvtt** [comment]
Added changing redirect instance, check it out in the new version
